<?php

/**
 * @file
 * Install hook to trigger CKEditor migration.
 */

/**
 * Implements hook_install().
 */
function iq_ckeditor4_to_ckeditor5_migration_install() {
  /** @var \Drupal\ckeditor4_to_5_migrator\MigratorInterface $migrator */
  $migrator = \Drupal::service('iq_ckeditor4_to_ckeditor5_migration.migrator');
  $migrator->migrate();

  \Drupal::logger('iq_ckeditor4_to_ckeditor5_migration')->info('CKEditor migration completed successfully.');
}